### ISSUE TITLE
unable to create DB with MySQL 5.7.10

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#110]
After upgrading from MySQL 5.6 to the latest 5.7.10 I'm unable to create a new database.
```

C:\inetpub\wwwroot\spotweb>php upgrade-db.php
Updating schema..(mysql)
        Validating spots(messageid)
                Adding column messageid(VARCHAR(128)) to spots
        Validating spots(poster)
                Adding column poster(VARCHAR(128)) to spots
        Validating spots(title)
                Adding column title(VARCHAR(128)) to spots
        Validating spots(tag)
                Adding column tag(VARCHAR(128)) to spots
        Validating spots(category)
                Adding column category(INTEGER) to spots
        Validating spots(subcata)
                Adding column subcata(VARCHAR(64)) to spots
        Validating spots(subcatb)
                Adding column subcatb(VARCHAR(64)) to spots
        Validating spots(subcatc)
                Adding column subcatc(VARCHAR(64)) to spots
        Validating spots(subcatd)
                Adding column subcatd(VARCHAR(64)) to spots
        Validating spots(subcatz)
                Adding column subcatz(VARCHAR(64)) to spots
        Validating spots(stamp)
                Adding column stamp(UNSIGNED INTEGER) to spots
        Validating spots(reversestamp)
                Adding column reversestamp(INTEGER) to spots
        Validating spots(filesize)
                Adding column filesize(UNSIGNED BIGINTEGER) to spots
        Validating spots(moderated)
                Adding column moderated(BOOLEAN) to spots
        Validating spots(commentcount)
                Adding column commentcount(INTEGER) to spots
        Validating spots(spotrating)
                Adding column spotrating(INTEGER) to spots
        Validating spots(reportcount)
                Adding column reportcount(INTEGER) to spots
        Validating spots(spotterid)
                Adding column spotterid(VARCHAR(32)) to spots
        Validating spots(editstamp)
                Adding column editstamp(UNSIGNED INTEGER) to spots
        Validating spots(editor)
                Adding column editor(VARCHAR(128)) to spots
        Validating spotsfull(messageid)
                Adding column messageid(VARCHAR(128)) to spotsfull
        Validating spotsfull(verified)
                Adding column verified(BOOLEAN) to spotsfull
        Validating spotsfull(usersignature)
                Adding column usersignature(VARCHAR(255)) to spotsfull
        Validating spotsfull(userkey)
                Adding column userkey(VARCHAR(512)) to spotsfull
        Validating spotsfull(xmlsignature)
                Adding column xmlsignature(VARCHAR(255)) to spotsfull
        Validating spotsfull(fullxml)
                Adding column fullxml(TEXT) to spotsfull
        Validating usenetstate(infotype)
                Adding column infotype(VARCHAR(128)) to usenetstate
        Validating usenetstate(curarticlenr)
                Adding column curarticlenr(INTEGER) to usenetstate
        Validating usenetstate(curmessageid)
                Adding column curmessageid(VARCHAR(128)) to usenetstate
        Validating usenetstate(lastretrieved)
                Adding column lastretrieved(INTEGER) to usenetstate
        Validating usenetstate(nowrunning)
                Adding column nowrunning(INTEGER) to usenetstate
        Validating commentsxover(messageid)
                Adding column messageid(VARCHAR(128)) to commentsxover
        Validating commentsxover(nntpref)
                Adding column nntpref(VARCHAR(128)) to commentsxover
        Validating commentsxover(spotrating)
                Adding column spotrating(INTEGER) to commentsxover
        Validating commentsxover(moderated)
                Adding column moderated(BOOLEAN) to commentsxover
        Validating commentsxover(stamp)
                Adding column stamp(UNSIGNED INTEGER) to commentsxover
        Validating reportsxover(messageid)
                Adding column messageid(VARCHAR(128)) to reportsxover
        Validating reportsxover(fromhdr)
                Adding column fromhdr(VARCHAR(256)) to reportsxover
        Validating reportsxover(keyword)
                Adding column keyword(VARCHAR(128)) to reportsxover
        Validating reportsxover(nntpref)
                Adding column nntpref(VARCHAR(128)) to reportsxover
        Validating spotstatelist(messageid)
                Adding column messageid(VARCHAR(128)) to spotstatelist
        Validating spotstatelist(ouruserid)
                Adding column ouruserid(INTEGER) to spotstatelist
        Validating spotstatelist(download)
                Adding column download(INTEGER) to spotstatelist
        Validating spotstatelist(watch)
                Adding column watch(INTEGER) to spotstatelist
        Validating spotstatelist(seen)
                Adding column seen(INTEGER) to spotstatelist
        Validating commentsfull(messageid)
                Adding column messageid(VARCHAR(128)) to commentsfull
        Validating commentsfull(fromhdr)
                Adding column fromhdr(VARCHAR(128)) to commentsfull
        Validating commentsfull(stamp)
                Adding column stamp(INTEGER) to commentsfull
        Validating commentsfull(usersignature)
                Adding column usersignature(VARCHAR(255)) to commentsfull
        Validating commentsfull(userkey)
                Adding column userkey(VARCHAR(512)) to commentsfull
        Validating commentsfull(spotterid)
                Adding column spotterid(VARCHAR(32)) to commentsfull
        Validating commentsfull(hashcash)
                Adding column hashcash(VARCHAR(255)) to commentsfull
        Validating commentsfull(body)
                Adding column body(TEXT) to commentsfull
        Validating commentsfull(verified)
                Adding column verified(BOOLEAN) to commentsfull
        Validating commentsfull(avatar)
                Adding column avatar(TEXT) to commentsfull
        Validating settings(name)
                Adding column name(VARCHAR(128)) to settings
        Validating settings(value)
                Adding column value(TEXT) to settings
        Validating settings(serialized)
                Adding column serialized(boolean) to settings
        Validating commentsposted(ouruserid)
                Adding column ouruserid(INTEGER) to commentsposted
        Validating commentsposted(messageid)
                Adding column messageid(VARCHAR(128)) to commentsposted
        Validating commentsposted(inreplyto)
                Adding column inreplyto(VARCHAR(128)) to commentsposted
        Validating commentsposted(randompart)
                Adding column randompart(VARCHAR(32)) to commentsposted
        Validating commentsposted(rating)
                Adding column rating(INTEGER) to commentsposted
        Validating commentsposted(body)
                Adding column body(TEXT) to commentsposted
        Validating commentsposted(stamp)
                Adding column stamp(INTEGER) to commentsposted
        Validating spotsposted(messageid)
                Adding column messageid(VARCHAR(128)) to spotsposted
        Validating spotsposted(ouruserid)
                Adding column ouruserid(INTEGER) to spotsposted
        Validating spotsposted(stamp)
                Adding column stamp(UNSIGNED INTEGER) to spotsposted
        Validating spotsposted(title)
                Adding column title(VARCHAR(128)) to spotsposted
        Validating spotsposted(tag)
                Adding column tag(VARCHAR(128)) to spotsposted
        Validating spotsposted(category)
                Adding column category(INTEGER) to spotsposted
        Validating spotsposted(subcats)
                Adding column subcats(VARCHAR(255)) to spotsposted
        Validating spotsposted(filesize)
                Adding column filesize(UNSIGNED BIGINTEGER) to spotsposted
        Validating spotsposted(fullxml)
                Adding column fullxml(TEXT) to spotsposted
        Validating reportsposted(ouruserid)
                Adding column ouruserid(INTEGER) to reportsposted
        Validating reportsposted(messageid)
                Adding column messageid(VARCHAR(128)) to reportsposted
        Validating reportsposted(inreplyto)
                Adding column inreplyto(VARCHAR(128)) to reportsposted
        Validating reportsposted(randompart)
                Adding column randompart(VARCHAR(32)) to reportsposted
        Validating reportsposted(body)
                Adding column body(TEXT) to reportsposted
        Validating reportsposted(stamp)
                Adding column stamp(INTEGER) to reportsposted
        Validating usersettings(userid)
                Adding column userid(INTEGER) to usersettings
        Validating usersettings(privatekey)
                Adding column privatekey(TEXT) to usersettings
        Validating usersettings(publickey)
                Adding column publickey(TEXT) to usersettings
        Validating usersettings(avatar)
                Adding column avatar(TEXT) to usersettings
        Validating usersettings(otherprefs)
                Adding column otherprefs(TEXT) to usersettings
        Validating users(username)
                Adding column username(VARCHAR(128)) to users
        Validating users(firstname)
                Adding column firstname(VARCHAR(128)) to users
        Validating users(passhash)
                Adding column passhash(VARCHAR(40)) to users
        Validating users(lastname)
                Adding column lastname(VARCHAR(128)) to users
        Validating users(mail)
                Adding column mail(VARCHAR(128)) to users
        Validating users(apikey)
                Adding column apikey(VARCHAR(32)) to users
        Validating users(lastlogin)
                Adding column lastlogin(INTEGER) to users
        Validating users(lastvisit)
                Adding column lastvisit(INTEGER) to users
        Validating users(lastread)
                Adding column lastread(INTEGER) to users
        Validating users(lastapiusage)
                Adding column lastapiusage(INTEGER) to users
        Validating users(deleted)
                Adding column deleted(BOOLEAN) to users
        Validating sessions(sessionid)
                Adding column sessionid(VARCHAR(128)) to sessions
        Validating sessions(userid)
                Adding column userid(INTEGER) to sessions
        Validating sessions(hitcount)
                Adding column hitcount(INTEGER) to sessions
        Validating sessions(lasthit)
                Adding column lasthit(INTEGER) to sessions
        Validating sessions(ipaddr)
                Adding column ipaddr(VARCHAR(45)) to sessions
        Validating sessions(devicetype)
                Adding column devicetype(VARCHAR(8)) to sessions
        Validating securitygroups(name)
                Adding column name(VARCHAR(128)) to securitygroups
        Validating grouppermissions(groupid)
                Adding column groupid(INTEGER) to grouppermissions
        Validating grouppermissions(permissionid)
                Adding column permissionid(INTEGER) to grouppermissions
        Validating grouppermissions(objectid)
                Adding column objectid(VARCHAR(128)) to grouppermissions
        Validating grouppermissions(deny)
                Adding column deny(BOOLEAN) to grouppermissions
        Validating usergroups(userid)
                Adding column userid(INTEGER) to usergroups
        Validating usergroups(groupid)
                Adding column groupid(INTEGER) to usergroups
        Validating usergroups(prio)
                Adding column prio(INTEGER) to usergroups
        Validating notifications(userid)
                Adding column userid(INTEGER) to notifications
        Validating notifications(stamp)
                Adding column stamp(INTEGER) to notifications
        Validating notifications(objectid)
                Adding column objectid(VARCHAR(128)) to notifications
        Validating notifications(type)
                Adding column type(VARCHAR(128)) to notifications
        Validating notifications(title)
                Adding column title(VARCHAR(128)) to notifications
        Validating notifications(body)
                Adding column body(TEXT) to notifications
        Validating notifications(sent)
                Adding column sent(BOOLEAN) to notifications
        Validating filters(userid)
                Adding column userid(INTEGER) to filters
        Validating filters(filtertype)
                Adding column filtertype(VARCHAR(128)) to filters
        Validating filters(title)
                Adding column title(VARCHAR(128)) to filters
        Validating filters(icon)
                Adding column icon(VARCHAR(128)) to filters
        Validating filters(torder)
                Adding column torder(INTEGER) to filters
        Validating filters(tparent)
                Adding column tparent(INTEGER) to filters
        Validating filters(tree)
                Adding column tree(TEXT) to filters
        Validating filters(valuelist)
                Adding column valuelist(TEXT) to filters
        Validating filters(sorton)
                Adding column sorton(VARCHAR(128)) to filters
        Validating filters(sortorder)
                Adding column sortorder(VARCHAR(128)) to filters
        Validating filters(enablenotify)
                Adding column enablenotify(BOOLEAN) to filters
        Validating filtercounts(userid)
                Adding column userid(INTEGER) to filtercounts
        Validating filtercounts(filterhash)
                Adding column filterhash(VARCHAR(40)) to filtercounts
        Validating filtercounts(currentspotcount)
                Adding column currentspotcount(INTEGER) to filtercounts
        Validating filtercounts(lastvisitspotcount)
                Adding column lastvisitspotcount(INTEGER) to filtercounts
        Validating filtercounts(lastupdate)
                Adding column lastupdate(INTEGER) to filtercounts
        Validating spotteridblacklist(spotterid)
                Adding column spotterid(VARCHAR(32)) to spotteridblacklist
        Validating spotteridblacklist(ouruserid)
                Adding column ouruserid(INTEGER) to spotteridblacklist
        Validating spotteridblacklist(idtype)
                Adding column idtype(INTEGER) to spotteridblacklist
        Validating spotteridblacklist(origin)
                Adding column origin(VARCHAR(255)) to spotteridblacklist
        Validating spotteridblacklist(doubled)
                Adding column doubled(BOOLEAN) to spotteridblacklist
        Validating cache(resourceid)
                Adding column resourceid(VARCHAR(128)) to cache
        Validating cache(cachetype)
                Adding column cachetype(INTEGER) to cache
        Validating cache(stamp)
                Adding column stamp(INTEGER) to cache
        Validating cache(metadata)
                Adding column metadata(TEXT) to cache
        Validating cache(ttl)
                Adding column ttl(INTEGER) to cache
        Validating moderatedringbuffer(messageid)
                Adding column messageid(VARCHAR(128)) to moderatedringbuffer
        Validating permaudit(stamp)
                Adding column stamp(INTEGER) to permaudit
        Validating permaudit(userid)
                Adding column userid(INTEGER) to permaudit
        Validating permaudit(permissionid)
                Adding column permissionid(INTEGER) to permaudit
        Validating permaudit(objectid)
                Adding column objectid(VARCHAR(128)) to permaudit
        Validating permaudit(result)
                Adding column result(BOOLEAN) to permaudit
        Validating permaudit(ipaddr)
                Adding column ipaddr(VARCHAR(45)) to permaudit
        Validating debuglog(stamp)
                Adding column stamp(INTEGER) to debuglog
        Validating debuglog(microtime)
                Adding column microtime(VARCHAR(16)) to debuglog
        Validating debuglog(level)
                Adding column level(INTEGER) to debuglog
        Validating debuglog(message)
                Adding column message(TEXT) to debuglog
        Validating index idx_spots_1
                Adding index idx_spots_1


SpotWeb crashed

Database schema or settings upgrade failed:
   42000: 1064: You have an error in your SQL syntax; check the manual that corr
esponds to your MySQL server version for the right syntax to use near 'IGNORE TA
BLE spots ADD UNIQUE INDEX idx_spots_1(messageid)' at line 1


#0 C:\inetpub\wwwroot\spotweb\lib\dbstruct\SpotStruct_mysql.php(97): dbeng_pdo->
rawExec('ALTER IGNORE TA...')
#1 C:\inetpub\wwwroot\spotweb\lib\dbstruct\SpotStruct_abs.php(131): SpotStruct_m
ysql->addIndex('idx_spots_1', 'UNIQUE', 'spots', Array)
#2 C:\inetpub\wwwroot\spotweb\lib\dbstruct\SpotStruct_abs.php(693): SpotStruct_a
bs->validateIndex('idx_spots_1', 'UNIQUE', 'spots', Array)
#3 C:\inetpub\wwwroot\spotweb\lib\services\Upgrade\Services_Upgrade_Base.php(42)
: SpotStruct_abs->updateSchema()
#4 C:\inetpub\wwwroot\spotweb\upgrade-db.php(44): Services_Upgrade_Base->databas
e()
#5 {main}
C:\inetpub\wwwroot\spotweb>
```

**Comment by dizney** [comment]
From the 5.7 ALTER TABLE documentation:

> As of MySQL 5.7.4, the IGNORE clause for ALTER TABLE is removed and its use produces an error.

**Comment by jaapjolman** [comment]
I also have the same issue!

is there a fix?

**Comment by Sweepr** [comment]
From the manual:
"IGNORE is a MySQL extension to standard SQL. It controls how ALTER TABLE works
if there are duplicates on unique keys in the new table or if warnings occur
when strict mode is enabled. If IGNORE is not specified, the copy is aborted and
rolled back if duplicate-key errors occur. If IGNORE is specified, only the
first row is used of rows with duplicates on a unique key. The other conflicting
rows are deleted. Incorrect values are truncated to the closest matching
acceptable value."

So, you could try to remove the IGNORE statement from lin 97 in SpotStruct_,mysql.php in \lib\dbstruct\ if this works then try to upgrade-db.php a few times and look for error's.

**Comment by dsadsdadsadsadsds** [comment]
That should fix it - the "IGNORE" part of ALTER TABLE is a MySQL-ism which the SpotStruct_PgSql.php does not employ either

**Comment by mesa57** [comment]
But that could be in the way of future database upgrades.

**Comment by dsadsdadsadsadsds** [comment]
The "ALTER TABLE IGNORE" is basically a big hack that tells the database to ignore logical corruption (duplicate entries where should have been none).

I would not do the copying the complete table personally. An alter table in MySQL itself almost always does this internally, so there is no use case - it is also very difficult to get this correct in a atomic way using MySQL.

PostgreSQL has transactional DDL so it would be a huge waste to do that on Postgres as it garantuees a stable schema. As the PostgreSQL DbStruct implementation just has  dummy implementatin of the 'ALTER TABLE x IGNORE' statement - it means it's just superfluous for MySQL as well.

**Comment by mesa57** [comment]
As long as an index does not change from non-unique to unique, I suppose a simple alter table would work. But if it does, a separate procedure has to be followed. As I think this will happen very rare, I would agree on discarding the IGNORE clause. But ... it should be tested :wink:

**Comment by dsadsdadsadsadsds** [comment]
Agreed.

Just some additional information - for the specific migrations not able to be handled by the very basic and hacky SpotStruct code, there is the manual migration statements in SpotUpgrade. So the use-case for changing a non-unique to an unique index would (sanely) never happen using SpotStruct.

**Comment by Sweepr** [comment]
@Rouzax, @jaapjolman 

Could either one of you confirm the proposed fix works?

**Comment by jaapjolman** [comment]
if you tell me what to do, i can check if it works

**Comment by Sweepr** [comment]
remove the IGNORE statement from line 97 in SpotStruct_,mysql.php in \lib\dbstruct\

**Comment by Sweepr** [comment]
@Rouzax, @jaapjolman so? did it work?

**Comment by jaapjolman** [comment]
yeah that solved it

**Comment by Sweepr** [comment]
Great, thank you for the update..

**Comment by basnagel** [comment]
Running the install.php it also stops at somekind of IGNORE error at the last step, create database.

> 42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your 
MySQL server version for the right syntax to use near 'IGNORE TABLE spots ADD UNIQUE INDEX idx_spots_1(messageid)' at line 1
Please correct the errors in below form and try again

Does this fix also relate to the above error?

**Comment by Sweepr** [comment]
Yes, that's the exact same error and this fix does apply.

**Comment by mesa57** [comment]
Will be changed in one of the coming commits (already tested).

**Comment by Rouzax** [comment]
@mesa57,  is this already in the Master branch? I need to rebuild my server because of a let's encrypt issue and would like to use mysql 5.7 from the start.

**Comment by mesa57** [comment]
No, not yet. 
As other member are desperatly trying to merge the master into the media branch, I cannot do any commits now. 
However, the change is not more then leaving out the IGNORE word, which you can do you're self.

**Comment by mesa57** [comment]
Solved in last commit, closing issue.
