### ISSUE TITLE
php 5.6.16 unable to retrieve spots with SSL

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#115]
when using php 5.6.0 on windows SSL retrieve works fine if I upgrade to php 5.6.16 I get this message:

```
C:\inetpub\wwwroot\spotweb>php retrieve.php
Last retrieve at 01/01/70 01:00:00
Retrieving new Spots from server news.cheapnews.eu...
Appr. Message count:    2201223
First message number:   5698531
Last message number:    7899754
Current article number: 6043597

Retrieving 6043597 till 6048598 (parsed: 5000, in DB: 1, signed: 4922, invalid:
78, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 4.6 seconds
Retrieving 6048598 till 6053599 (parsed: 5001, in DB: 0, signed: 4907, invalid:
94, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.75 seconds
Retrieving 6053599 till 6058600 (parsed: 5001, in DB: 0, signed: 4900, invalid:
101, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 5.67 seconds
Retrieving 6058600 till 6063601 (parsed: 5001, in DB: 0, signed: 4895, invalid:
106, rtntn.skip: 0, mod: 0, full: 0, total: 5001) in 6.63 seconds
SpotWeb v0.67.28.31 on PHP v5.6.16 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 C:\inetpub\wwwroot\spotweb\NNTP\Protocol\Client.php(296): Net_NNTP_Protocol_C
lient->throwError('Failed to read ...')
#1 C:\inetpub\wwwroot\spotweb\NNTP\Protocol\Client.php(279): Net_NNTP_Protocol_C
lient->_getStatusResponse()
#2 C:\inetpub\wwwroot\spotweb\NNTP\Protocol\Client.php(1759): Net_NNTP_Protocol_
Client->_sendCommand('XOVER 6063601-6...')
#3 C:\inetpub\wwwroot\spotweb\NNTP\Client.php(1000): Net_NNTP_Protocol_Client->c
mdXOver('6063601-6068601')
#4 C:\inetpub\wwwroot\spotweb\lib\services\Nntp\Services_Nntp_Engine.php(137): N
et_NNTP_Client->getOverview('6063601-6068601')
#5 C:\inetpub\wwwroot\spotweb\lib\services\Retriever\Services_Retriever_Base.php
(213): Services_Nntp_Engine->getOverview(6063601, 6068601)
#6 C:\inetpub\wwwroot\spotweb\lib\services\Retriever\Services_Retriever_Base.php
(319): Services_Retriever_Base->loopTillEnd('6043597', '5000')
#7 C:\inetpub\wwwroot\spotweb\retrieve.php(154): Services_Retriever_Base->perfor
m()
#8 {main}

Finished retrieving spots.
```

**Comment by Sweepr** [comment]
So don't use php 5.6.16 ;-)

**Comment by mesa57** [comment]
Know issue https://github.com/spotweb/spotweb/issues/65
Just do not use ssl.

**Comment by Rouzax** [comment]
Okay, did not know that the same issue also applied to Windows.
