### ISSUE TITLE
PHP Fatal error MYSQL_ATTR_FOUND_ROWS

### ISSUE THREAD

**Issue by mbnn** [spotweb/spotweb#134]
Hello all,

Since today (latest ubuntu 15 update) im getting this with the cron/manual php retrieve:
(PDO/MYSQL 	5.6.28, PHP 5.6.17)

HP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_FOUND_ROWS' in /home/plexone/public_html/spotweb/lib/dbeng/dbeng_pdo_mysql.php:28
Stack trace:
#0 /home/plexone/public_html/spotweb/lib/Bootstrap.php(100): dbeng_pdo_mysql->connect('localhost', 'spotweb', 'password', 'spotweb')
#1 /home/plexone/public_html/spotweb/lib/Bootstrap.php(34): Bootstrap->getDaoFactory()
#2 /home/plexone/public_html/spotweb/retrieve.php(20): Bootstrap->boot()
#3 {main}
  thrown in /home/plexone/public_html/spotweb/lib/dbeng/dbeng_pdo_mysql.php on line 28

When i click retrieve in spotweb itself, it works fine.
Any idea?

**Comment by mbnn** [comment]
Looks like the new ubuntu update Xenial (16) has php 7 and i fixed this by typing:
apt-get install php-mysql
apt-get install php-curl

:)
