### ISSUE TITLE
Retrieve.php with --debug gives error

### ISSUE THREAD

**Issue by JustFogMaxi** [spotweb/spotweb#141]
When using Retrieve.php with --debug option it throws an error. Without --debug retrieve seems to works.

```
Removing Spot information which is beyond retention period,, done
WARNING: Using slow PHP based RSA, please enable the PHP OpenSSL extension whenever possible
Last retrieve at 01/01/70 01:00:00
Retrieving new Spots from server news.Usenetserver.com...
Appr. Message count: 	2790257
First message number:	2
Last message number:	2790259
Current article number:	2

Retrieving 2 till 503

SpotWeb v0.67.28.31 on PHP v5.6.20 crashed

Fatal error occured retrieving reports:
  22001: 1406: Data too long for column 'message' at row 1



#0 C:\www\spotweb\lib\dbeng\dbeng_pdo.php(74): dbeng_pdo->exec('INSERT INTO deb...', Array)
#1 C:\www\spotweb\lib\dao\Base\Dao_Base_DebugLog.php(25): dbeng_pdo->modify('INSERT INTO deb...', Array)
#2 C:\www\spotweb\lib\SpotDebug.php(28): Dao_Base_DebugLog->add(10, 1459925709.0352, 'hdrList=a:501:{...')
#3 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Spots.php(209): SpotDebug::msg(10, 'hdrList=a:501:{...')
#4 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '2', 503, 1459925708.8068)
#5 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('0', '500')
#6 C:\www\spotweb\retrieve.php(154): Services_Retriever_Base->perform()
#7 {main}

Finished retrieving spots.
```

**Comment by mesa57** [comment]
Did see that error too. It is about insert into the debuglog table which fails.
Think I already corrected that somewhere in the code, but not yet commited to the repo.

**Comment by Sweepr** [comment]
@mesa57, you mean this one?

**Comment by mesa57** [comment]
No, that one is about the reportsxover table. This is about the debuglog tables.
Although it contains a field type TEXT, even that has a limit.
I encountered one run which was trying to fill that field with a million or so characters. 
The fix is : truncation to 2000 characters as more is not sensible in the debuglog.

**Comment by mesa57** [comment]
Solved in last commit, closing issue.
