### ISSUE TITLE
Retrieve.php Truncate error after every finish

### ISSUE THREAD

**Issue by JustFogMaxi** [spotweb/spotweb#144]
Getting this error on every retrieve finish. Seems to work ok, nontheless.

```
Retrieving 61062 till 62063, found 1001 reports in 1.53 seconds
Retrieving 62063 till 63064, found 1001 reports in 1.39 seconds
Retrieving 63064 till 64065, found 1001 reports in 1.86 seconds
Retrieving 64065 till 65066, found 1001 reports in 1.44 seconds
Retrieving 65066 till 66067, found 1001 reports in 0.9 seconds
Retrieving 66067 till 67068, found 1001 reports in 0.43 seconds
Retrieving 67068 till 68069, found 1001 reports in 0.88 seconds
Retrieving 68069 till 69070, found 1001 reports in 1.87 seconds
Retrieving 69070 till 70071, found 1001 reports in 0.55 seconds
Retrieving 70071 till 71072, found 1001 reports in 0.72 seconds


SpotWeb v0.67.28.31 on PHP v5.6.20 crashed

Fatal error occured retrieving reports:
  22007: 1292: Truncated incorrect DOUBLE value: 'pXH6u96gFCIdOZjVANl3A@spot.net
'



#0 C:\www\spotweb\lib\dbeng\dbeng_pdo.php(74): dbeng_pdo->exec('UPDATE spots \n\
t...', Array)
#1 C:\www\spotweb\lib\dao\Base\Dao_Base_Spot.php(304): dbeng_pdo->modify('UPDATE
 spots \n\t...')
#2 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Reports.php(132): Da
o_Base_Spot->updateSpotReportCount(Array)
#3 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Base.php(227): Servi
ces_Retriever_Reports->process(Array, 70071, 71072, 1459975901.2776)
#4 C:\www\spotweb\lib\services\Retriever\Services_Retriever_Base.php(319): Servi
ces_Retriever_Base->loopTillEnd('1002', '1000')
#5 C:\www\spotweb\retrieve.php(206): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving reports.

```

**Comment by mesa57** [comment]
Cannot reproduce this. Please specify : 
- OS/version used, PHP version, Database engine.

Meanwhile you can try to uncheck this : 

![retrieve](http://content.screencast.com/users/mesa57/folders/Jing/media/75b0eff0-2b27-4470-9623-25b2f63de0ab/2016-04-07_1055.png)

**Comment by Sweepr** [comment]
@JustFogMaxi 

Look like you have some double's in your table, Could you try to truncate the reportsxover table, then run upgrade-db.php once again..

Then try again,.

**Comment by JustFogMaxi** [comment]
Strange, it seems to have fixed itself... It could be because I was trying things out yesterday, killing and restarting 'retrieve.php --force' a couple of times. Sorry for wasting your time, haha.
