### ISSUE TITLE
HP Fatal error:  Uncaught Error: Cannot use string offset as an array

### ISSUE THREAD

**Issue by Rouzax** [spotweb/spotweb#270]
OS: Server 2016
PHP 7.1.1 X64
Spotweb: 681c8e9

```
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisDisplay' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 73
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisFormat' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisName' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisUnit' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Abscissa' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'AbsicssaPosition' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 78
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Axis' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80
[27-Feb-2017 19:28:43 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php:80
Stack trace:
#0 C:\inetpub\wwwroot\spotweb\lib\services\Image\Services_Image_Chart.php(28): pData->__construct()
#1 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(108): Services_Image_Chart->renderChart('3Dpie', 'Spots per categ...', Array, Array)
#2 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(60): Services_Providers_Statistics->createStatsPerCategory('')
#3 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(36): Services_Providers_Statistics->renderStatImage('spotspercategor...', '')
#4 C:\inetpub\wwwroot\spotweb\retrieve.php(250): Services_Providers_Statistics->createAllStatistics()
#5 {main}
  thrown in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisDisplay' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 73
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisFormat' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 74
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisName' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 75
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'XAxisUnit' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 76
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Abscissa' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Cannot assign an empty string to a string offset in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 77
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'AbsicssaPosition' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 78
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Warning:  Illegal string offset 'Axis' in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80
[27-Feb-2017 19:34:11 Europe/Amsterdam] PHP Fatal error:  Uncaught Error: Cannot use string offset as an array in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php:80
Stack trace:
#0 C:\inetpub\wwwroot\spotweb\lib\services\Image\Services_Image_Chart.php(28): pData->__construct()
#1 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(108): Services_Image_Chart->renderChart('3Dpie', 'Spots per categ...', Array, Array)
#2 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(60): Services_Providers_Statistics->createStatsPerCategory('')
#3 C:\inetpub\wwwroot\spotweb\lib\services\Providers\Services_Providers_Statistics.php(36): Services_Providers_Statistics->renderStatImage('spotspercategor...', '')
#4 C:\inetpub\wwwroot\spotweb\retrieve.php(250): Services_Providers_Statistics->createAllStatistics()
#5 {main}
  thrown in C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart\class\pData.class.php on line 80

```

**Comment by mesa57** [comment]
Is pChart already php 7.1 compatible ? If no, can you file an issue with them ?

**Comment by Rouzax** [comment]
It looks like pChart is pretty dead as project. 
The forum has no new posts since 2014 and the latest update to pChart seems to be from 2011 http://wiki.pchart.net/doc.imagemaps.replaceimagemaptitle.html

Did find a github repo that claims to have updated the pChart library to PHP 7.1
https://github.com/bozhinov/pChart2.0-for-PHP7

**Comment by mesa57** [comment]
A while ago other developers have decided to bring all vendor packages under composer.
That means that only updates via componer are done and accepted. 
Advantage is of course that most (but apparently not all) packages are up to date. 
For now please use the bozhinov package for you're self. If after some time of testing it appears to run well we could may decide to get it out of composer into a seperate folder.

**Comment by Rouzax** [comment]
I've removed everything from `C:\inetpub\wwwroot\spotweb\vendor\jean-damien\pchart` and copied the repo from https://github.com/bozhinov/pChart2.0-for-PHP7 in there.
Will keep you posted on the progress

**Comment by mesa57** [comment]
Master branche updated. Btw statistics didn't work at all due to a cache problem.
Now working 😄
