### ISSUE TITLE
Fatal retrieve error & mysql exception at first run

### ISSUE THREAD

**Issue by pl0ng** [spotweb/spotweb#301]
Hi,

I'm experiencing a combination of 2 errors on a first time run of Spotweb. Here below my server setup:
Dedicated Ubuntu 16.10; Php7.015; Nginx 1.10.1; Mysql 5.7.17

**My specific install:**
Git clone -> install.php (all checks good) -> php upgrade-db.php (all checks good)
Immediately afterwards, retrieve.php started up in screen. 
No .htpasswd set up.

**Errors:**
When going to http://server/spotweb/index.php, after the upgrade-db step, I get the following:
```
Notice: Array to string conversion in /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php on line 57

Notice: Array to string conversion in /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php on line 57

Notice: Array to string conversion in /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php on line 57
SpotWeb v0.68.28.32 on PHP v7.0.15-0ubuntu0.16.10.4 crashed object(SqlErrorException)#16 (8) { ["message":protected]=> string(74) "HY000: 1366: Incorrect integer value: 'Array' for column 'userid' at row 1" ["string":"CustomException":private]=> NULL ["code":protected]=> int(-1) ["file":protected]=> string(45) "/var/www/html/spotweb/lib/dbeng/dbeng_pdo.php" ["line":protected]=> int(59) ["trace":"Exception":private]=> array(5) { [0]=> array(6) { ["file"]=> string(45) "/var/www/html/spotweb/lib/dbeng/dbeng_pdo.php" ["line"]=> int(74) ["function"]=> string(4) "exec" ["class"]=> string(9) "dbeng_pdo" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(155) "INSERT INTO sessions(sessionid, userid, hitcount, lasthit, ipaddr, devicetype) VALUES(:sessionid, :userid, :hitcount, :lasthit, :ipaddr, :devicetype)" [1]=> array(6) { [":sessionid"]=> array(2) { [0]=> string(60) "2l5j053ewhp89a750efmx56djhy1h2v7fcxzjyjyadfzbn44clu9fyiikzw0" [1]=> int(2) } [":userid"]=> array(2) { [0]=> array(0) { } [1]=> int(1) } [":hitcount"]=> array(2) { [0]=> int(1) [1]=> int(1) } [":lasthit"]=> array(2) { [0]=> int(1492581929) [1]=> int(1) } ["ipaddr"]=> array(2) { [0]=> string(13) " ***redacted_external_IP*** " [1]=> int(2) } ["devicetype"]=> array(2) { [0]=> string(4) "full" [1]=> int(2) } } } } [1]=> array(6) { ["file"]=> string(55) "/var/www/html/spotweb/lib/dao/Base/Dao_Base_Session.php" ["line"]=> int(52) ["function"]=> string(6) "modify" ["class"]=> string(9) "dbeng_pdo" ["type"]=> string(2) "->" ["args"]=> array(2) { [0]=> string(155) "INSERT INTO sessions(sessionid, userid, hitcount, lasthit, ipaddr, devicetype) VALUES(:sessionid, :userid, :hitcount, :lasthit, :ipaddr, :devicetype)" [1]=> array(6) { [":sessionid"]=> array(2) { [0]=> string(60) "2l5j053ewhp89a750efmx56djhy1h2v7fcxzjyjyadfzbn44clu9fyiikzw0" [1]=> int(2) } [":userid"]=> array(2) { [0]=> array(0) { } [1]=> int(1) } [":hitcount"]=> array(2) { [0]=> int(1) [1]=> int(1) } [":lasthit"]=> array(2) { [0]=> int(1492581929) [1]=> int(1) } ["ipaddr"]=> array(2) { [0]=> string(13) " ***redacted_external_IP*** " [1]=> int(2) } ["devicetype"]=> array(2) { [0]=> string(4) "full" [1]=> int(2) } } } } [2]=> array(6) { ["file"]=> string(72) "/var/www/html/spotweb/lib/services/User/Services_User_Authentication.php" ["line"]=> int(58) ["function"]=> string(10) "addSession" ["class"]=> string(16) "Dao_Base_Session" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> array(6) { ["sessionid"]=> string(60) "2l5j053ewhp89a750efmx56djhy1h2v7fcxzjyjyadfzbn44clu9fyiikzw0" ["userid"]=> array(0) { } ["hitcount"]=> int(1) ["lasthit"]=> int(1492581929) ["ipaddr"]=> string(13) " ***redacted_external_IP*** " ["devicetype"]=> string(4) "full" } } } [3]=> array(6) { ["file"]=> string(72) "/var/www/html/spotweb/lib/services/User/Services_User_Authentication.php" ["line"]=> int(121) ["function"]=> string(16) "createNewSession" ["class"]=> string(28) "Services_User_Authentication" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> array(0) { } } } [4]=> array(6) { ["file"]=> string(31) "/var/www/html/spotweb/index.php" ["line"]=> int(36) ["function"]=> string(17) "useOrStartSession" ["class"]=> string(28) "Services_User_Authentication" ["type"]=> string(2) "->" ["args"]=> array(1) { [0]=> bool(false) } } } ["previous":"Exception":private]=> NULL ["string":"Exception":private]=> string(0) "" } HY000: 1366: Incorrect integer value: 'Array' for column 'userid' at row 1
```

The retrieve.php step ends in following error:
```
Processed a total of 13403270 comments
Finished retrieving comments.

Last retrieve at Wed 19 Apr 2017 05:50:50 AM CEST
Retrieving new reports from server ***
Appr. Message count:    187068
First message number:   50413
Last message number:    237481
Current article number: 50413

Retrieving 50413 till 55414, found 5001 reports in 0.52 seconds
Retrieving 55414 till 60415, found 5001 reports in 0.35 seconds
Retrieving 60415 till 65416, found 5001 reports in 0.48 seconds
Retrieving 65416 till 70417, found 5001 reports in 0.41 seconds

SpotWeb v0.68.28.32 on PHP v7.0.15-0ubuntu0.16.10.4 crashed

Fatal error occured retrieving reports:
  22007: 1292: Truncated incorrect DOUBLE value: '1UpaGppUiPYc7epTgAMhS@spot.net'



#0 /var/www/html/spotweb/lib/dbeng/dbeng_pdo.php(74): dbeng_pdo->exec('UPDATE spots \n\t...', Array)
#1 /var/www/html/spotweb/lib/dao/Base/Dao_Base_Spot.php(270): dbeng_pdo->modify('UPDATE spots \n\t...')
#2 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Reports.php(132): Dao_Base_Spot->updateSpotReportCount(Array)
#3 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Reports->process(Array, 65416, 70417, 1492573860.9297)
#4 /var/www/html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(70417, '5000')
#5 /var/www/html/spotweb/retrieve.php(197): Services_Retriever_Base->perform()
#6 {main}

Finished retrieving reports.

```

The mysql log itself is empty.
Full deletion and reinstall of the software ends in the same results.

TIA

**Comment by Starcreature** [comment]
Hello pl0ng,

It looks like there is a duplication in your database. You can try to search for the messageid and delete this message  like:

DELETE FROM reportsxover WHERE messageid = '1UpaGppUiPYc7epTgAMhS@spot.net'
DELETE FROM reportsposted WHERE messageid = '1UpaGppUiPYc7epTgAMhS@spot.net'

**Comment by mesa57** [comment]
As for the first error : 
It looks like a session cookie is passed to spotweb without a userid.
I cannot repeat this error.
As to the second : also that error is not repeatable, so impossible to debug.
