### ISSUE TITLE
Unable to retrieve

### ISSUE THREAD

**Issue by WorkaholicGoT** [spotweb/spotweb#57]
I haven't been able to retrieve / update my spotweb database since 29-03-2015.

Receiving the following error when manualy starting the retrieve job:

spotweb@webserver:~/domains/spotweburl/private_html/spotweb$ php retrieve.php 
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 29 Mar 2015 03:30:29 PM CEST
Retrieving new Spots from server news.cheapnews.eu...

Warning: stream_socket_client(): unable to connect to tcp://news.cheapnews.eu:119 (Connection timed out) in /home/spotweb/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php on line 693
SpotWeb v0.68.29.32 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
(-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]

#0 /home/spotweb/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /home/spotweb/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /home/spotweb/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /home/spotweb/domains/spotweburl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#4 {main}

**Comment by WorkaholicGoT** [comment]
I tried changing usenet server but having the same problem. Usenet server is working fine on my own pc and nothing has been changed on this server.

**Comment by Sweepr** [comment]
Is the port 119 open?  is it forwarding?

Check your firewall

**Comment by WorkaholicGoT** [comment]
It s not a security or port issue because there has been no changes in the security or port configuration. But I double checked this to be safe with manual connectivity on these ports (I even tried ssl).

This error seems to be a Connectivity problem but its actually not (I had similar errors but it had something to do with corrupt headers on the usp side)

**Comment by WorkaholicGoT** [comment]
I noticed it is could have something to do with having  group free.pt?or headers in this group? See the error?

**Comment by Sweepr** [comment]
Short answer to your last would be, No.

I'm not sure how the IP config on your server and router are setup, but i can tell you:

If you can connect from your PC to the USP, then that's fine, this has nothing todo with the groups, or headers. if for some reason your spotweb server cannot connect to the USP then there is something wrong on your internal network to the outside with that server of router firewall settings.

This error: "unable to connect to tcp://news.cheapnews.eu:119 (Connection timed out)" simply means port 119 on is closed.

Can you ping tcp://news.cheapnews.eu from the spotweb box?

**Comment by WorkaholicGoT** [comment]
Yes I can connect directly from my spotweb server to these usp's (tried both) and ports are ok to. Ping and connection with telnet method works fine

**Comment by WorkaholicGoT** [comment]
Like I said I have seen these errors before and they are also being given when it loses it connection due to a corrupt spot and it the connection is then somehow disconnected making it seem that it's having connection issues

**Comment by Sweepr** [comment]
Could you setup a log for the retrieve and post it here?

Do you see this error every single time retrieve runs or do you see that it sometimes is able to make a connection?

**Comment by WorkaholicGoT** [comment]
Every time..

**Comment by WorkaholicGoT** [comment]
But only since the 29th of March and like I said nothing has changed on my end (neither have I changed or updated anything)

**Comment by kaibosh** [comment]
Seeing a similar error since yesterday. No local changes made to spotweb in the last months. Noticed this issue started after an update to PHP. Works with SSL turned off. Perhaps related to recent PHP certificate handling changes and not every USP having clean certs.

**Comment by Wally73** [comment]
after you had the corrupted spot did you checked and repaired your database??

**Comment by WorkaholicGoT** [comment]
I did check my database by running the pho upgrade database command.

I have disabled ssl and am connecting on the default port so the solution from kaibush doesn't work. I did recently update my Debian packages though.. And php was included I believe.. 

We need to see if we can get better debugging/logging because the error message doesn't help

**Comment by Wally73** [comment]
I use Apache/2.4.10 (Debian) PHP/5.6.6-2, Server MPM: prefork, Server
Built: Mar 15 2015 on debian Jessie and have no issues at all in retrieving
stuff so it is YOUR  setup

**Comment by Sweepr** [comment]
After a search on google this popped up:

http://www.synology-forum.nl/spotweb/spotweb-installatie-error-while-connecting-to-server/

Take a look at this please..

**Comment by WorkaholicGoT** [comment]
@Sweepr 
It's not a synology environment, this is a direct git pull from spotweb git. So should not be the issue. 

@Wally73 
How do I check if these headers are working with USP or not? I have no idea.. I have USP accounts for supernews and cheapnews..

**Comment by Sweepr** [comment]
@WorkaholicGoT 

Yes, does not matter is it's a synology environment, point is that it's exactly the same error as you are getting so this may point into the direction to look for, just trying to help ok?

I have no idea why you even start retrieve.php --reallyforce -retro if you don;t even have an idea what it's doing.

I'm not going to waste more time on this issue, as for me there is none,.

**Comment by Wally73** [comment]
Normally you only use retrieve.php (if that one doesnt work (or it
complains its already running) you do one run with --reallyforce (and then
back to the normal retrieve again)
--retro it goes back to the start date you've entered  (also only runned
once)

headering with grabIt https://www.binaries4all.com/grabit/headers.php
headering with Newsleecher
https://www.binaries4all.com/newsleecher/headers.php

**Comment by WorkaholicGoT** [comment]
@Sweepr 

Not sure why you are annoyed that you closed this topic :). I just said it's not a package issue and I'm using the git depository.. 

Anyways.. the problem has not been resolved.. the retro eventually also ran into the same problem.
Can you please reopen?


kroket@webserver:~/domains/spotweburl/private_html/spotweb$ php retrieve.php --reallyforce
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 29 Mar 2015 03:30:29 PM CEST
Retrieving new Spots from server news.eu.supernews.com...
Appr. Message count:    3961823
First message number:   3118
Last message number:    3964941
Current article number: 3963210

Retrieving 3963210 till 3964211
getHeader(): Failed to retrieve article: <xv0aiA3vDEkMvwXVQOyhO@spot.net>

getHeader(): Failed to retrieve article: <btPzjqaYRJUQvwXVQ0N8a@spot.net>

getHeader(): Failed to retrieve article: <G4qnH32TOawOPwXVQdOIY@spot.net>

getHeader(): Failed to retrieve article: <Ly79c2KoGJIJPwXVQU6cg@spot.net>
SpotWeb v0.68.29.32 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(296): Net_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(279): Net_NNTP_Protocol_Client->_getStatusResponse()
#2 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(1140): Net_NNTP_Protocol_Client->_sendCommand('HEAD <Ly79c2KoG...')
#3 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Client.php(515): Net_NNTP_Protocol_Client->cmdHead('<Ly79c2KoGJIJPw...')
#4 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(282): Net_NNTP_Client->getHeader('<Ly79c2KoGJIJPw...')
#5 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php(160): Services_Nntp_Engine->getHeader('<Ly79c2KoGJIJPw...')
#6 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(398): Services_Nntp_SpotReading->readFullSpot('Ly79c2KoGJIJPwX...')
#7 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '3963210', 3964211, 1427907386.85)
#8 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('3963210', '1000')
#9 /home/kroket/domains/spotweburl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#10 {main}



#0 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(296): Net_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(279): Net_NNTP_Protocol_Client->_getStatusResponse()
#2 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(1140): Net_NNTP_Protocol_Client->_sendCommand('HEAD <Ly79c2KoG...')
#3 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Client.php(515): Net_NNTP_Protocol_Client->cmdHead('<Ly79c2KoGJIJPw...')
#4 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(282): Net_NNTP_Client->getHeader('<Ly79c2KoGJIJPw...')
#5 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php(160): Services_Nntp_Engine->getHeader('<Ly79c2KoGJIJPw...')
#6 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(398): Services_Nntp_SpotReading->readFullSpot('Ly79c2KoGJIJPwX...')
#7 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '3963210', 3964211, 1427921805.96)
#8 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('3963210', '1000')
#9 /home/kroket/domains/spotweburl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#10 {main}

**Comment by WorkaholicGoT** [comment]
I signed up for another trial USP account and tested this both with SSL and SSL off. Receiving this error (free.pt again?)


kroket@webserver:~/domains/spotweburl/private_html/spotweb$ php retrieve.php --reallyforce
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 29 Mar 2015 03:30:29 PM CEST
Retrieving new Spots from server free.hitnews.com...

Warning: stream_socket_client(): unable to connect to tcp://free.hitnews.com:119 (Connection timed out) in /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php on line 693
SpotWeb v0.68.29.32 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Error while connecting to server (server did not respond) [response: ""] [response: ""]


#0 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(120): Services_Nntp_Engine->connect()
#1 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(112): Services_Nntp_Engine->selectGroup('free.pt')
#2 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(280): Services_Retriever_Base->connect(Array)
#3 /home/kroket/domains/spotweburl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#4 {main}

**Comment by WorkaholicGoT** [comment]
A last resort could be to back-up database, dump the spots contents and do a new retrieve and see what happends..

But hopefully you guys have other debugging idea's, because a complete retrieve will take days.

**Comment by Sweepr** [comment]
Re-opend on request, no hard feelings.

Thought the issue had been resolved as you were able to retrieve using the retrieve.php --reallyforce -retro command.

**Comment by WorkaholicGoT** [comment]
Another retry with a free USP trial account is giving this : 
spotweburl@webserver:~/domains/spotweburl.nl/private_html/spotweb$ php retrieve.php 
Removing Spot information which is beyond retention period,, done
Last retrieve at Sun 29 Mar 2015 03:30:29 PM CEST
Retrieving new Spots from server free.hitnews.com...
Looking for articlenumber for messageid
Searching from 2357548 to 2362549
Appr. Message count:    2362547
First message number:   2
Last message number:    2362549
Current article number: 2360690

Retrieving 2360690 till 2361691
getHeader(): Failed to retrieve article: <xv0aiA3vDEkMvwXVQOyhO@spot.net>

getHeader(): Failed to retrieve article: <btPzjqaYRJUQvwXVQ0N8a@spot.net>

getHeader(): Failed to retrieve article: <Ly79c2KoGJIJPwXVQU6cg@spot.net>

getHeader(): Failed to retrieve article: <G4qnH32TOawOPwXVQdOIY@spot.net>
SpotWeb v0.68.29.32 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(296): Net_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(279): Net_NNTP_Protocol_Client->_getStatusResponse()
#2 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(1140): Net_NNTP_Protocol_Client->_sendCommand('HEAD <G4qnH32TO...')
#3 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/NNTP/Client.php(515): Net_NNTP_Protocol_Client->cmdHead('<G4qnH32TOawOPw...')
#4 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(282): Net_NNTP_Client->getHeader('<G4qnH32TOawOPw...')
#5 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php(160): Services_Nntp_Engine->getHeader('<G4qnH32TOawOPw...')
#6 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(398): Services_Nntp_SpotReading->readFullSpot('G4qnH32TOawOPwX...')
#7 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, 2360690, 2361691, 1427923521.31)
#8 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(2360690, '1000')
#9 /home/spotweburl/domains/spotweburl.nl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#10 {main}

**Comment by Sweepr** [comment]
Did you try to change this:

Retrieve increment
Lower this if you get timeouts during retrieve:

Set to 1000 or 500?

**Comment by WorkaholicGoT** [comment]
Yes, it was set to 1000, but 500 gives the same error above.

**Comment by Sweepr** [comment]
Best way would be to truncate spots and spotsfull and the try another retrieve

**Comment by WorkaholicGoT** [comment]
it's running.. let's hope this solves the problem :)

**Comment by WorkaholicGoT** [comment]
Too bad.. after a couple of minutes retrieving it gave the following error :(

Retrieving 2154727 till 2155228 (parsed: 62, in DB: 0, signed: 0, invalid: 0, rtntn.skip: 62, mod: 0, full: 0, total: 62) in 0.02 seconds
Retrieving 2155228 till 2155729 (parsed: 501, in DB: 0, signed: 0, invalid: 0, rtntn.skip: 501, mod: 0, full: 0, total: 501) in 0.13 seconds
Retrieving 2155729 till 2156230 (parsed: 501, in DB: 0, signed: 0, invalid: 0, rtntn.skip: 501, mod: 0, full: 0, total: 501) in 0.1 seconds
Retrieving 2156230 till 2156731 (parsed: 501, in DB: 0, signed: 0, invalid: 0, rtntn.skip: 501, mod: 0, full: 0, total: 501) in 0.18 seconds
Retrieving 2156731 till 2157232 (parsed: 501, in DB: 0, signed: 0, invalid: 1, rtntn.skip: 500, mod: 0, full: 0, total: 501) in 0.15 seconds
Retrieving 2157232 till 2157733 (parsed: 501, in DB: 0, signed: 0, invalid: 3, rtntn.skip: 498, mod: 0, full: 0, total: 501) in 1.49 seconds
Retrieving 2157733 till 2158234 (parsed: 501, in DB: 0, signed: 0, invalid: 1, rtntn.skip: 500, mod: 0, full: 0, total: 501) in 1.43 seconds
Retrieving 2158234 till 2158735 (parsed: 501, in DB: 0, signed: 0, invalid: 1, rtntn.skip: 500, mod: 0, full: 0, total: 501) in 2.31 seconds
SpotWeb v0.68.29.32 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 /home/kroket/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(296): Net_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /home/kroket/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(279): Net_NNTP_Protocol_Client->_getStatusResponse()
#2 /home/kroket/domains/spotweburl.nl/private_html/spotweb/NNTP/Protocol/Client.php(1759): Net_NNTP_Protocol_Client->_sendCommand('XOVER 2158735-2...')
#3 /home/kroket/domains/spotweburl.nl/private_html/spotweb/NNTP/Client.php(1000): Net_NNTP_Protocol_Client->cmdXOver('2158735-2159235')
#4 /home/kroket/domains/spotweburl.nl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(137): Net_NNTP_Client->getOverview('2158735-2159235')
#5 /home/kroket/domains/spotweburl.nl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(213): Services_Nntp_Engine->getOverview(2158735, 2159235)
#6 /home/kroket/domains/spotweburl.nl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd(0, '500')
#7 /home/kroket/domains/spotweburl.nl/private_html/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#8 {main}

**Comment by Sweepr** [comment]
Indeed very strange, try this:

truncate spots and spotsfull, commentsfull and commentsxover and try again.

**Comment by WorkaholicGoT** [comment]
#1701 - Cannot truncate a table referenced in a foreign key constraint (`kroket_spotweb`.`commentsfull`, CONSTRAINT `commentsfull_ibfk_1` FOREIGN KEY (`messageid`) REFERENCES `kroket_spotweb`.`commentsxover` (`messageid`)

**Comment by Sweepr** [comment]
Excuse me, first xover then full.

**Comment by WorkaholicGoT** [comment]
Getting the same error message :(

**Comment by Sweepr** [comment]
Could you try to empty the column 'messageid' from xover.. then truncate xover, full.. spots, spotsfull

Something really messed up your DB..

**Comment by Sweepr** [comment]
Maybe after the truncate perform an upgrade-db.php to verrify the tables are ok

**Comment by WorkaholicGoT** [comment]
All done.. even restored a working back-up of my complete spotweb user including an older version of github spotweb etc (without hover view and mediabranch) which was working perfectly.

The only thing I can think of is something with a latest update on my server (apt-get update) which included several ssl / php etc related stuff. 

Any further idea's on how to debug? 

kroket@webserver:~/domains/spotweburl/private_html/spotweb$ php retrieve.php --force
Removing Spot information which is beyond retention period,, done
Last retrieve at Wed 11 Feb 2015 05:30:26 PM CET
Retrieving new Spots from server news.eu.supernews.com...
Appr. Message count:    3962456
First message number:   3118
Last message number:    3965574
Current article number: 3865685

Retrieving 3865685 till 3866686
getHeader(): Failed to retrieve article: <eatE0UUaroMS4LbVAGkB0@spot.net>

getHeader(): Failed to retrieve article: <OjgtU7zagSkGYTbVAA2v2@spot.net>

getHeader(): Failed to retrieve article: <OjgtU7zagSkGYTbVAA2v2@spot.net>

getHeader(): Failed to retrieve article: <OjgtU7zagSkGYTbVAA2v2@spot.net>
SpotWeb v0.67.28.31 on PHP v5.5.23 crashed

Fatal error occured while connecting to the newsserver:
  (-1) Failed to read from socket...! [response: ""]


#0 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(296): Net_NNTP_Protocol_Client->throwError('Failed to read ...')
#1 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(279): Net_NNTP_Protocol_Client->_getStatusResponse()
#2 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Protocol/Client.php(1140): Net_NNTP_Protocol_Client->_sendCommand('HEAD <OjgtU7zag...')
#3 /home/kroket/domains/spotweburl/private_html/spotweb/NNTP/Client.php(515): Net_NNTP_Protocol_Client->cmdHead('<OjgtU7zagSkGYT...')
#4 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(282): Net_NNTP_Client->getHeader('<OjgtU7zagSkGYT...')
#5 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(295): Services_Nntp_Engine->getHeader('<OjgtU7zagSkGYT...')
#6 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_Engine.php(295): Services_Nntp_Engine->getHeader('<OjgtU7zagSkGYT...')
#7 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php(160): Services_Nntp_Engine->getHeader('<OjgtU7zagSkGYT...')
#8 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(398): Services_Nntp_SpotReading->readFullSpot('OjgtU7zagSkGYTb...')
#9 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '3865685', 3866686, 1427996560.98)
#10 /home/kroket/domains/spotweburl/private_html/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('3865685', '1000')
#11 /home/kroket/domains/spotweburl/private_html/spotweb/retrieve.php(154): Services_Retriever_Base->perform()
#12 {main}

**Comment by garbrecht** [comment]
Wil geen mail meer ontvangen aub

Op donderdag 2 april 2015 heeft WorkaholicGoT <notifications@github.com>
het volgende geschreven:

**Comment by Wally73** [comment]
@garbrecht: https://github.com/settings/notifications zet daar email uit
bij watching

**Comment by WzL** [comment]
Check your http://spotwebdomain/install.php for the required prerequisites being "OK". After my Upgrade to Jessy I had some not OK's.

**Comment by WorkaholicGoT** [comment]
Checked, everything is OK except for PostgreSQL and open base dir

Postgres not needed for mysql I think and open base dir has always been this way. 

Spotweb also works, it's just not being updated due to retrieve errors (see above)

**Comment by WorkaholicGoT** [comment]
The funny thing is that I'm seeing other public spotweb urls (found through google) also have the same problem. They do provide more debug info though.. 

 crashed object(NntpException)#24 (11) { ["_response":"NntpException":private]=> string(52) "Cant retrieve article, try joining a newsgroup first" ["message":protected]=> string(88) "No such article found [response: "Cant retrieve article, try joining a newsgroup first"]" ["string":"CustomException":private]

**Comment by WzL** [comment]
from a google: it is possible that the standard NNTP ports (119 and 563) are being blocked (either by your ISP or a firewall). Try setting your NNTP port to 80 (for non-ssl) or 443 (for ssl), if you’re news server supports it (many do).

**Comment by Sweepr** [comment]
@WzL, that what i thought too, but he said the he could connect and retrieve succesfully from his PC using the same USP as on his Spotweb server..

@WorkaholicGoT I'm currently running Spotweb using PHP v5.3.28 on CentOS release 6.6 (Final) with 5.5.41-37.0 - Percona Server and have never seen such error's before, 

Do you have the ability to set the native PHP for spotweb root folder to PHP5.3 or do a rollback

**Comment by WzL** [comment]
You could run a new test installation of spotweb (using a test database) and during the 2nd step of the installation verify the USP connection. See if the verification succeeds and if not what error is been thrown.

**Comment by WorkaholicGoT** [comment]
I am currently filling a new database now, it's timing out with the same error, but restarting it causes it to go further again. What I did change was the timeout php value from 30 to 300 (not sure if this has any effect at al)

**Comment by WzL** [comment]
I did not test this, but from the names of the tables i should say export and import the following tables: "filters", "settings","users" and "usersettings". Not sure about the unique keys/tables.

**Comment by WorkaholicGoT** [comment]
It's been running more than 8 hours now. Things I've changed:

- SSL off (using port 119)
- php timeout time 30 --> 300 seconds
- retrieve performance 1000 -> 500
- Clean database / restored back-up of older spotweb version (v0.67.28.31)

Let's hope it manages to completely retrieve, after that I'm kind of scared to update to the latest spotweb by using git pull. Might be a better idea to leave it this way.

**Comment by Sweepr** [comment]
After this is succesfull i woukd suggest you create a second "shadow" test/debug spotweb on the same server.. before actually merging a good running environment.

This way you'll never get into trouble like this and it's easier to debug 

That's how i do it ;-)

**Comment by dsadsdadsadsadsds** [comment]
When you get a connection or other retrieval error, dumpin the database is - no offence - a bad course of action. Spotweb is *very* resillient to database errors and will almost always repair itself. The most you could do is, for example, delete the last 15000 spots or something.

The proper way to debug this is to run retrieve.php with the ````--debug```` option and see where it went wrong. Honestly though, a connection error you are getting  is almost always either an USP error or an configuration error on your system.

**Comment by WorkaholicGoT** [comment]
The problem has been solved with the above steps.. It's fully retrieved now.

**Comment by Sweepr** [comment]
Ok, that wraps it up, closing this as the issue has been resolved.

**Comment by WorkaholicGoT** [comment]
Ok I managed to recreate this problem again. It's caused by using SSL with my USP (supernews) on port 563. This has always worked before, but I think it now is causing problems due to the recent patches for SSL security etc. 

As a work around I will keep using 119 and non SSL, but I suggest we still look into this issue and see why it's connecting to my USP and having retrieval errors using SSL wtih spotweb. With my local download client I can connect fine to the same port and retrieve data from the same USP. Some is going wrong with the PHP on this webserver icm spotweb.

**Comment by dsadsdadsadsadsds** [comment]
Spotweb uses the SSL library provided by PHP which in turn is provided by your OS. If you update the OS (eg: update your php5-openssl package) it might start working again.

**Comment by WorkaholicGoT** [comment]
This  has been updated due to the security risks recently and ssl is working fine for other services. Any clue why it's not working for the spotweb retrieve?

**Comment by dsadsdadsadsadsds** [comment]
Not really. Perhaps you can ask your USP to see if they can assist you with this issue?

**Comment by WzL** [comment]
Since i upgraded to Debian Jessy I had this Root CA and intermediate CA
certificate issue which were not unknown by the PHP installation or openssl
installation thus it spit out an error in regards to SSL. I did have to
manually download the certs, and configure PHP.ini to the location of these
public certificates. PHP did spit an error message at that moment in
regards to SSL, so that is defenately different in this case. Maybe this is
also the cause here, i do not know. Just a heads up.

2015-04-03 20:38 GMT+02:00 dsadsdadsadsadsds <notifications@github.com>:

> Not really. Perhaps you can ask your USP to see if they can assist you
> with this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spotweb/spotweb/issues/57#issuecomment-89385400>.
>



-- 
Met vriendelijke groet,

With kind regards,

Mit freundlichen Grüßen,

Distinti saluti,

Atentos saludos,


Jacco Onderdijk
