### ISSUE TITLE
upgrade_db.php fails when switching from master to media

### ISSUE THREAD

**Issue by klara31** [spotweb/spotweb#58]
I just switched from main to media. When executing `php upgrade-db.php`, I consistently get the following error:
```
...
	Validating index idx_users_4
	Validating index idx_sessions_1
	Validating index idx_sessions_2
	Validating index idx_sessions_3
	Validating index idx_sessionsrel_1
	Validating index idx_spotstatelist_1
	Validating index idx_spotstatelistrel_1
	Validating index idx_securitygroups_1
	Validating index idx_grouppermissions_1
	Validating index idx_usergroups_1
	Validating index idx_usergroupsrel_1
	Validating index idx_notifications_1
	Validating index idx_notifications_2
	Validating index idx_filters_1
	Validating index idx_filtercounts_1
	Validating index idx_spotteridblacklist_1
	Validating index idx_spotteridblacklist_2
	Validating index idx_cache_1
	Validating index idx_cache_2
	Validating index idx_moderatedringbuffer_1
	Validating index idx_mastercollections_1
	Validating index idx_collections_1
	Validating index idx_tmdbinfo_1
	Validating index idx_tmdbtrailers_1
	Validating index idx_tmdbcredits_1
	Validating index idx_tmdbcast_1
	Validating index idx_tmdbcrew_1
	Validating index idx_tmdbimages_1
Schema update done
Updating settings
Settings update done


SpotWeb crashed

Database schema or settings upgrade failed:
   23000: 1062: Duplicate entry '3-31-pushover' for key 'idx_grouppermissions_1'


#0 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Users.php(468): dbeng_pdo->rawExec('INSERT INTO gro...')
#1 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Users.php(19): Services_Upgrade_Users->updateSecurityGroups(false)
#2 /var/www/spotweb/lib/services/Upgrade/Services_Upgrade_Base.php(35): Services_Upgrade_Users->update()
#3 /var/www/spotweb/upgrade-db.php(50): Services_Upgrade_Base->users(Object(Services_Settings_Container))
#4 {main}
```

This error also occurs when starting from scratch, so `git pull` the source and also build the database from scratch

**Comment by Sweepr** [comment]
did you use install.php?

**Comment by klara31** [comment]
Yes: all OK

**Comment by Sweepr** [comment]
Duplicate entry '3-31-pushover' for key 'idx_grouppermissions_1'

Try to run php upgrade-db.php --reset-securitygroups

**Comment by dsadsdadsadsadsds** [comment]
With @Sweepr, but also.

You are only able to get this error if you eithre modified default groups (not possible with the UI, so a manual database modification), or if you upgraded Spotweb and then downgraded again.

Both options are not really advised, so please tell us what you did as you might be running into more troubles in the long run.

**Comment by klara31** [comment]
I have completely started from scratch: removed database, removed /var/www/spotweb. Ran through install.php, so far so good.

When running retrieve, I bump into the following issue:
```
Last retrieve at Thu 01 Jan 1970 01:00:00 AM CET
Retrieving new Spots from server reader.extremeusenet.nl...
Appr. Message count: 	1533959
First message number:	1670671
Last message number:	3204630
Current article number:	1670671

Retrieving 1670671 till 1675672PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
...
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/lib/dbeng/dbeng_pdo.php on line 175


SpotWeb v0.68.29.32 on PHP v5.5.12-2ubuntu4.3 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' at line 1 (SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' at line 1)



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(146): dbeng_pdo->exec('SELECT messagei...', Array)
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php(606): dbeng_pdo->arrayQuery('SELECT messagei...')
#2 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(216): Dao_Base_Spot->matchSpotMessageIds(Array)
#3 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '1670671', 1675672, 1428309381.8658)
#4 /var/www/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('0', '5000')
#5 /var/www/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#6 {main}
```

**Comment by Sweepr** [comment]
@klara31 


If there is no matched field name in the table schema, this error will occur.

Something's completly messed up here, not sure what happend or how to recover from this.
Beter

**Comment by WzL** [comment]
I experience the same behaviour icw php 5.6.6-2 and MySQL Ver 14.14 Distrib 5.5.42.

Clean git pull, install.php succeeds configuring new (truncated) DB, Spotweb is accessible and functioning properly. First retrieve though throws the same error as above. This behaviour happens only on Media Branch, no problem on Master.

**Comment by Sweepr** [comment]
@klara31 , @WzL 

What does your dbsettings.inc.php file state are 

$dbsettings['engine'] =

**Comment by WzL** [comment]
```
cat dbsettings.inc.php | grep engine
$dbsettings['engine'] = 'pdo_mysql';

**Comment by Sweepr** [comment]
That's seems ok, 
I'm also running the media branch and i have not yet ran into any of the above problems.

What's to output if you run retrieve --debug

**Comment by WzL** [comment]
```php retrieve.php --reallyforce --debug &> error.msg

``` cat error.msg
Last retrieve at Thu Jan  1 01:00:00 1970
Retrieving new Spots from server reader.haregruwelijkhe.id...
Appr. Message count:    1813388
First message number:   5698531
Last message number:    7511919
Current article number: 5698531

Retrieving 5698531 till 5703532PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/spotweb/lib/dbeng/dbeng_pdo.php on line 175
....
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/spotweb/lib/dbeng/dbeng_pdo.php on line 175
PHP Warning:  PDO::quote() expects parameter 1 to be string, array given in /var/www/spotweb/spotweb/lib/dbeng/dbeng_pdo.php on line 175


SpotWeb v0.68.29.32 on PHP v5.6.6-2 crashed

Fatal error occured retrieving reports:
  42000: 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' at line 1 (SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,' at line 1)



#0 /var/www/spotweb/spotweb/lib/dbeng/dbeng_pdo.php(146): dbeng_pdo->exec('SELECT messagei...', Array)
#1 /var/www/spotweb/spotweb/lib/dao/Base/Dao_Base_Spot.php(606): dbeng_pdo->arrayQuery('SELECT messagei...')
#2 /var/www/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Spots.php(216): Dao_Base_Spot->matchSpotMessageIds(Array)
#3 /var/www/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(227): Services_Retriever_Spots->process(Array, '5698531', 5703532, 1428441739.3529)
#4 /var/www/spotweb/spotweb/lib/services/Retriever/Services_Retriever_Base.php(319): Services_Retriever_Base->loopTillEnd('0', '5000')
#5 /var/www/spotweb/spotweb/retrieve.php(155): Services_Retriever_Base->perform()
#6 {main}

**Comment by Sweepr** [comment]
@wzl, i'm running Percona Server 5.5.41-37.0 Release 37.0, Rev 727 , Spotweb is running on PHP Version 5.3.28

**Comment by WzL** [comment]
Ok if i diff between the two branches, these are the changes:

```
diff /var/www/spotweb/master/lib/dbeng/dbeng_pdo.php /var/www/spotweb/media/lib/dbeng/dbeng_pdo.php
59c59
<             throw new SqlErrorException(implode(': ', $x->errorInfo), -1);
---
>             throw new SqlErrorException(implode(': ', $x->errorInfo) . ' (' . $x->getMessage() . ')', -1);
73c73
<
---
>
124c124
<         $row = $stmt->fetch();
---
>         $row = $stmt->fetch(PDO::FETCH_NUM);
147c147
<               $tmpArray = $stmt->fetchAll();
---
>               $tmpArray = $stmt->fetchAll(PDO::FETCH_ASSOC);
159a160
>      * @param $forceType
160a162
>      * @throws NotImplementedException
162,164c164,170
<     function safe($s) {
<         if (is_integer($s) || is_double($s)) {
<             return $s;
---
>     function safe($s, $forceType = null) {
>         if ($forceType === null) {
>             if (is_integer($s) || is_double($s)) {
>                 return $s;
>             } else {
>                 return $this->_conn->quote($s);
>             } # else
166,167c172,179
<             return $this->_conn->quote($s);
<         } # else
---
>             if ($forceType == PDO::PARAM_INT) {
>                 return (float) $s;
>             } elseif ($forceType == PDO::PARAM_STR) {
>                 return $this->_conn->quote($s);
>             } else {
>                 throw new NotImplementedException("Unknown forcetype passed to safe()");
>             } // else
>         } // else

**Comment by Sweepr** [comment]
Can you find this:

When you add phpinfo.php to your webroot and browse to spotweb/phpinfo.php 

<?php

// Show all information, defaults to INFO_ALL
phpinfo();

?>

Do you see anything that looks like this?

PDO
PDO support	enabled
PDO drivers 	mysql, sqlite

**Comment by WzL** [comment]
i got:

PDO
PDO support	enabled
PDO drivers 	mysql
pdo_mysql
PDO Driver for MySQL	enabled
Client API version 	5.5.42

**Comment by Sweepr** [comment]
Running out of idea's at this time..

Few things i'd like to see, what happens when you change :

$dbsettings['engine'] = 'pdo_mysql';

Into 

$dbsettings['engine'] = 'mysql';

If this does not change anything,

Open your php.ini file and look for these extensions below.  
Comment them out and see what happens.

extension=pdo.so
extension=pdo_mysql.so

**Comment by rolo20** [comment]
I had the same issue. With phpmyadmin deleted the entry and run upgrade-db.php again. Problem solved.

**Comment by Sweepr** [comment]
Try now: 

https://github.com/spotweb/spotweb/commit/041181f25a6f00225b4eb0cd44a8ef8dd27cf303

**Comment by Sweepr** [comment]
See: https://github.com/spotweb/spotweb/issues/60
