### ISSUE TITLE
Unknown column 'spotsposted.ouruserid' in 'where clause'

### ISSUE THREAD

**Issue by Fossil01** [spotweb/spotweb#728]
```
Appr. Message count: 	5206873
First message number:	3118
Last message number:	5209991
Current article number:	5209989

Retrieving 5209989 till 5209992 (parsed: 2, in DB: 1, signed: 2, invalid: 0, rtntn.skip: 0, mod: 0, full: 0, total: 3) in 0.07 seconds
Processed a total of 3 spots
Finished retrieving spots.

Calculating how many spots are new

SpotWeb v0.68.33.34 on PHP v7.4.26 crashed

Fatal error occured retrieving reports:
  42S22: 1054: Unknown column 'spotsposted.ouruserid' in 'where clause'



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(154): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php(751): dbeng_pdo->singleQuery()
#2 /var/www/spotweb/lib/services/Actions/Services_Actions_CacheNewSpotCount.php(166): Dao_Base_Spot->getSpotCount()
#3 /var/www/spotweb/retrieve.php(159): Services_Actions_CacheNewSpotCount->cacheNewSpotCount()
#4 {main}

Finished retrieving spots.
```

I checked my DB but in the spotsposted table the column does exist.

My php_errors.log shows:

`PHP Notice:  Undefined index: userid in /var/www/spotweb/lib/services/Search/Services_Search_QueryParser.php on line 63`

**Comment by Fossil01** [comment]
I am on master branch by the way.

**Comment by mesa57** [comment]
Try the develop branch please.

**Comment by Sweepr** [comment]
25 day's no activity, closing

Re-open if needed.

**Comment by Fossil01** [comment]
Updates to PHP 8.1 and develop branch.

```
Calculating how many spots are new

SpotWeb v0.68.33.34 on PHP v8.1.1 crashed

Fatal error occured retrieving reports:
  42S22: 1054: Unknown column 'spots.ouruserid' in 'where clause'



#0 /var/www/spotweb/lib/dbeng/dbeng_pdo.php(154): dbeng_pdo->exec()
#1 /var/www/spotweb/lib/dao/Base/Dao_Base_Spot.php(751): dbeng_pdo->singleQuery()
#2 /var/www/spotweb/lib/services/Actions/Services_Actions_CacheNewSpotCount.php(171): Dao_Base_Spot->getSpotCount()
#3 /var/www/spotweb/retrieve.php(159): Services_Actions_CacheNewSpotCount->cacheNewSpotCount()
#4 {main}

Finished retrieving spots.
```

**Comment by mesa57** [comment]
Question: do you have a own filter defined with you're own spots ?

**Comment by mesa57** [comment]
Please remove any filter with you're own spots. Retriever cannot determine a user-id during execution. so is not able to count the number of spots then. Only use the My Spots filter in the top of the filter menu.

**Comment by Fossil01** [comment]
Ah, I don't have any Spots. The filter is just a global one which every user can see (filtering some specific HD content), whcih comes from a DB table IIRC. So I don't think we were talking about the same thing.

**Comment by mesa57** [comment]
The only way I can reproduce you're error is by including a filter with own spot counts.
Is you're system used by many users ?

**Comment by mesa57** [comment]
Issue should be resolved on develop branch.

**Comment by Fossil01** [comment]
Awesome, will test.

**Comment by Fossil01** [comment]
Fixed

**Comment by mesa57** [comment]
Thanks for testing 😃
