### ISSUE TITLE
The operation has timed out (interactive search problem with Sonarr/Radarr)

### ISSUE THREAD

**Issue by moostmartijn** [spotweb/spotweb#803]
**Describe the bug/issue**
Whenever I start an interactive search (search monitored) within Sonarr/Radarr, and *arr wants to grab an NZB from Spotweb, Spotweb will fail to download and I receive the following message in the log (of Sonarr):

```
2023-01-28 10:14:06.8|Error|Sabnzbd|Downloading nzb for episode 'Yellowjackets S01E07 HDR 2160p WEB H265' failed (http://192.168.1.11:9696/9/download?apikey=(removed)&link=WFA5YnZwTG9MNW1XUU4rVWJ4M216eWxJVzZNRnRqbW5FdjJRTXBkVE5SaU44NXBHWEx1VmVlM2d0c0orME0yK1V1dng2SVZ1QkxPYmVzK2RzTlpldXY1ZTk4Z0dKZDVxTlpObVc4ZlV3RTBZQm1Sa3VYNnhhRFR4Q0cwVWlQMENqN05Fd0gyWVVFdWhSTmhFRWR5NGluc1I0alhubi9WYll2Sm5rWFB5cGpBPQ&file=Yellowjackets+S01E07+HDR+2160p+WEB+H265)

[v3.0.9.1549] System.Net.WebException: The operation has timed out.: 'http://192.168.1.11:9696/9/download?apikey=(removed)&link=WFA5YnZwTG9MNW1XUU4rVWJ4M216eWxJVzZNRnRqbW5FdjJRTXBkVE5SaU44NXBHWEx1VmVlM2d0c0orME0yK1V1dng2SVZ1QkxPYmVzK2RzTlpldXY1ZTk4Z0dKZDVxTlpObVc4ZlV3RTBZQm1Sa3VYNnhhRFR4Q0cwVWlQMENqN05Fd0gyWVVFdWhSTmhFRWR5NGluc1I0alhubi9WYll2Sm5rWFB5cGpBPQ&file=Yellowjackets+S01E07+HDR+2160p+WEB+H265' ---> System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000e8] in /spksrc/native/mono/work-native/mono-5.20.1.34/mcs/class/System/System.Net/HttpWebRequest.cs:956 
  at System.Net.HttpWebRequest.GetResponse () [0x0000f] in /spksrc/native/mono/work-native/mono-5.20.1.34/mcs/class/System/System.Net/HttpWebRequest.cs:1218 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x00123] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:81 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001c0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:107 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x00086] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:126 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:59 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:281 
  at NzbDrone.Core.Download.UsenetClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00057] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\UsenetClientBase.cs:48 

2023-01-28 10:14:08.9|Warn|ProcessDownloadDecisions|Couldn't add report to download queue. Yellowjackets S01E07 HDR 2160p WEB H265

[v3.0.9.1549] NzbDrone.Core.Exceptions.ReleaseDownloadException: Downloading nzb failed ---> System.Net.WebException: The operation has timed out.: 'http://192.168.1.11:9696/9/download?apikey=(removed)&link=WFA5YnZwTG9MNW1XUU4rVWJ4M216eWxJVzZNRnRqbW5FdjJRTXBkVE5SaU44NXBHWEx1VmVlM2d0c0orME0yK1V1dng2SVZ1QkxPYmVzK2RzTlpldXY1ZTk4Z0dKZDVxTlpObVc4ZlV3RTBZQm1Sa3VYNnhhRFR4Q0cwVWlQMENqN05Fd0gyWVVFdWhSTmhFRWR5NGluc1I0alhubi9WYll2Sm5rWFB5cGpBPQ&file=Yellowjackets+S01E07+HDR+2160p+WEB+H265' ---> System.Net.WebException: The operation has timed out.
  at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000e8] in /spksrc/native/mono/work-native/mono-5.20.1.34/mcs/class/System/System.Net/HttpWebRequest.cs:956 
  at System.Net.HttpWebRequest.GetResponse () [0x0000f] in /spksrc/native/mono/work-native/mono-5.20.1.34/mcs/class/System/System.Net/HttpWebRequest.cs:1218 
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x00123] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:81 
   --- End of inner exception stack trace ---
  at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookies) [0x001c0] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:107 
  at NzbDrone.Common.Http.HttpClient.ExecuteRequest (NzbDrone.Common.Http.HttpRequest request, System.Net.CookieContainer cookieContainer) [0x00086] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:126 
  at NzbDrone.Common.Http.HttpClient.Execute (NzbDrone.Common.Http.HttpRequest request) [0x00008] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:59 
  at NzbDrone.Common.Http.HttpClient.Get (NzbDrone.Common.Http.HttpRequest request) [0x00007] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Common\Http\HttpClient.cs:281 
  at NzbDrone.Core.Download.UsenetClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00057] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\UsenetClientBase.cs:48 
   --- End of inner exception stack trace ---
  at NzbDrone.Core.Download.UsenetClientBase`1[TSettings].Download (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x0016e] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\UsenetClientBase.cs:75 
  at NzbDrone.Core.Download.DownloadService.DownloadReport (NzbDrone.Core.Parser.Model.RemoteEpisode remoteEpisode) [0x00271] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\DownloadService.cs:99 
  at NzbDrone.Core.Download.ProcessDownloadDecisions.ProcessDecisions (System.Collections.Generic.List`1[T] decisions) [0x00104] in M:\BuildAgent\work\63739567f01dbcc2\src\NzbDrone.Core\Download\ProcessDownloadDecisions.cs:77 

```

And Spotweb will become unavailable:
<img width="401" alt="Schermafbeelding 2023-01-28 om 10 18 56" src="https://user-images.githubusercontent.com/31592734/215258278-cc8eb35f-a521-4758-81ef-555914ebe7e7.png">

During the search, Spotweb is not accessible in a browser.

Short after the search is ready, Spotweb is available again. 
Manual search will also show Spotweb results and downloading an NZB is possible. 

**Have you searched the internet or Github for an answer?**
Yes, unfortunately I didn't find an answer

**To Reproduce**
Start an interactive search in Sonarr/Radarr, wait will Sonarr/Radarr grabs an NZB from Spotweb and Spotweb will fail.

**Expected behavior**
No failure of Spotweb NZB downloading by interactive search

**Screenshots**
Screenshots added.

**Desktop (please complete the following information):**
 - OS: Linux
 - Spotweb Version: where to find the version? It will be the latest, I installed everything yesterday
 - Master branch
 -  PHP version 7.4
 -  Synology NAS DS718+(with web station)
 

**Additional context**
Whenever downloading an NZB will fail from a different indexer, and the following NZB is from Spotweb, *arr does grab the one from Spotweb, so grabbing an NZB works.
Maybe it does too many API requests to Spotweb or something?

**Comment by Sweepr** [comment]
Are Spotweb and Sonarr/Radarr installed on the same device?

**Comment by moostmartijn** [comment]
Yes, both on my Synology

**Comment by Sweepr** [comment]
Then try to change the Indexer URL in Sonarr/Radarr in the URL section from `http://192.168.1.11:9696` into `http://127.0.0.1` <-- if install directly in the WWW root, i am not sure if this need any directory into which Spotweb is installed.

**Comment by moostmartijn** [comment]
I added the Spotweb branch in the web/spotweb folder and setup Web station. So I added `http://127.0.0.1/spotweb`
When I sync the Indexers from Prowlarr to Sonarr/Radarr, they both still show the old url: `http://192.168.1.11:9696`
<img width="718" alt="Schermafbeelding 2023-01-28 om 10 55 43" src="https://user-images.githubusercontent.com/31592734/215260029-4b1107c3-d5cb-49b8-b3db-518e601f48d2.png">

**Comment by moostmartijn** [comment]
Unfortunately it's still not working as expected...

This is the error in the log of Radarr:

```
2023-01-28 12:59:26.6|Error|Newznab|An error occurred while processing indexer feed. http://192.168.1.11:9696/9/api?t=movie&cat=2000,2030,2040,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=6079516

[v4.3.2.6857] System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: Software caused connection abort.
 ---> System.Net.Sockets.SocketException (103): Software caused connection abort
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.InitialFillAsync(Boolean async)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in D:\a\1\s\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 101
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request, CookieContainer cookieContainer) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 124
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in D:\a\1\s\src\NzbDrone.Common\Http\HttpClient.cs:line 59
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchIndexerResponse(IndexerRequest request) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 309
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchPage(IndexerRequest request, IParseIndexerResponse parser) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 292
   at NzbDrone.Core.Indexers.HttpIndexerBase`1.FetchReleases(Func`2 pageableRequestChainSelector, Boolean isRecent) in D:\a\1\s\src\NzbDrone.Core\Indexers\HttpIndexerBase.cs:line 123
FeedUrl: http://192.168.1.11:9696/9/api?t=movie&cat=2000,2030,2040,2050,2060&extended=1&apikey=(removed)&offset=0&limit=100&imdbid=6079516
```

After this search Spotweb is unavailable for *arr:
<img width="401" alt="Schermafbeelding 2023-01-28 om 10 18 56" src="https://user-images.githubusercontent.com/31592734/215265519-a07678be-8d52-4b07-952f-180ca4d056bc.png">

**Comment by Sweepr** [comment]
An error occurred while processing indexer feed. http://192.168.1.11:9696/9  ,is this your indexer?  if spotweb is located at `http://127.0.0.1/spotweb` then why does it still want to connect to `http://192.168.1.11:9696/9` ?

**Comment by moostmartijn** [comment]
Probably because I have the indexer in Prowlarr which syncs with Sonarr/Radarr, I will try to add Spotweb as an indexer directly in Sonarr/Radarr without Prowlarr and see if it solves the problem.

**Comment by moostmartijn** [comment]
The above solution to add 127.0.0.1/spotweb instead of 192.168.1.11:9696 (Prowlarr) fixed my problem, thanks Sweepr.

**Comment by Hydranet** [comment]
> The above solution to add 127.0.0.1/spotweb instead of 192.168.1.11:9696 (Prowlarr) fixed my problem, thanks Sweepr.
I have my setup in prowlarr without any issues and when I search my spotweb it doesn't give any errors when processing an nzb file. The only difference is I run spotweb with on it's on sub-domain with https and I run prowlarr on a subdirectory of a sub-domain with https and reverse proxy it.
