### ISSUE TITLE
NZB button makes file with name download with error message after update dsm Version: 7.1.1-42962 Update 5

### ISSUE THREAD

**Issue by Superbitcomputing** [spotweb/spotweb#822]
**Describe the bug/issue**
 - Spotweb version 1.5.4 with php 8.0 used on synology dsm Version: 7.1.1-42962 Update 5
 - NZB button normaly save filename.nzb on mij disk
 - now it saves always a file with a name download to disk with a error message in it
 - the error message is :
 - 
Fatal error: Uncaught Error: Call to undefined function gzinflate() in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php:164
Stack trace:
#0 /volume1/web/spotweb/lib/services/Providers/Services_Providers_Nzb.php(61): Services_Nntp_SpotReading->readBinary(Array, true)
#1 /volume1/web/spotweb/lib/services/Actions/Services_Actions_DownloadNzb.php(41): Services_Providers_Nzb->fetchNzb(Array)
#2 /volume1/web/spotweb/lib/page/SpotPage_getnzb.php(48): Services_Actions_DownloadNzb->handleNzbAction(Array, Array, 'display', Object(Services_Providers_FullSpot), Object(Services_Providers_Nzb))
#3 /volume1/web/spotweb/index.php(141): SpotPage_getnzb->render()
#4 {main}
  thrown in /volume1/web/spotweb/lib/services/Nntp/Services_Nntp_SpotReading.php on line 164

**Have you searched the internet or Github for an answer?** 
 - Yes for 4 days now normaly i can solve this kind of problems
 - did find Zlib compression and PHP8.x no longer compatible
 tried :
1. reinstall spoweb 
2. other php 7,4
3. rebuild spotwebdatabase and rebuild cache
4. changed zlib.output_compression = on in php.ini
5. 

**To Reproduce**
1. Go to spoweb
6. Click on spot and klik nzb button

7. save the file named called "download" and open with editor
8. See error

**Expected behavior**
 - Save de file.nzb to my disk

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11h22 fully updated
 - Browser chrome
 - Spotweb Version 1.5.4
 - Which branch  Master
 -  PHP version 8.0
 -  Device information NAS/Synology DS916+

**Additional context**
well i do not have any experians with linux or php so i can touch any code on my site 
i am really sorry to send this error seems on internet that i am the only one ?

**Comment by Sweepr** [comment]
`Call to undefined function gzinflate()`

Seems like you are missing a PHP library:  https://www.php.net/manual/en/book.zlib.php

**Comment by Superbitcomputing** [comment]
Thank you il will try to figer out how to installl his library
